# Generated by Django 4.1.4 on 2022-12-20 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=100, verbose_name='Фамилия риелтора')),
                ('name', models.CharField(max_length=100, verbose_name='Имя риелтора')),
                ('patronymic', models.CharField(max_length=100, verbose_name='Отчество риелтора')),
                ('share', models.IntegerField(verbose_name='Доля от комиссии')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.TimeField()),
                ('type', models.CharField(choices=[('MEETING', 'Meeting'), ('PRESENTATION', 'Presentation'), ('PHONE_CALL', 'Phone_call')], max_length=12)),
                ('duration', models.DurationField()),
                ('comment', models.CharField(max_length=200, verbose_name='Комментарий')),
                ('agent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.agent')),
            ],
        ),
    ]
